name: my_check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install PostgreSQL
        run: sudo apt install postgresql postgresql-contrib

      - name: Run PostgresQL
        run: sudo systemctl start postgresql.service

      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run flake8 linter
        run: |
          make lint
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.MY_SECRET_FOR_HEXLET_PROJECT_83 }}
        with:
          coverageCommand: make test-cov
          debug: true
